### PR TITLE
Support regions other than us-east-1

### PR DESCRIPTION
**Pull request by jtdoepke**
Some of the component names are hardcoded to `us-east-1`.

### CODE REVIEW

**Review by sblack4 — DISMISSED** [review]

**Comment by sblack4** [comment]
Good catch!

**Review by sblack4 — APPROVED** [review]
🔥

**Comment by sblack4** [comment]
@smiller171 @dgoodellrhy I want to get your eyes on this before the merge

**Review by smiller171 — APPROVED** [review]
Thanks for fixing this. Total oversight on my part

**Comment by smiller171** [comment]
@sblack4 this looks perfect. Can't believe I messed this up initially

**Pull request merged**
